name: Frontend

on:
  push:
    branches: [ develop,main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "âš¡ Checkout"
        uses: actions/checkout@v3
      
      - name: "ğŸ§ª Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "ğŸ“¦ Install Dependencies"
        working-directory: ./client
        run: yarn install --frozen-lockfile
        
      - name: "ğŸŒ¹ Format Code"
        working-directory: ./client
        run: yarn format

      - name: "ğŸ§¶ Lint Code"
        working-directory: ./client
        run: yarn lint
              
      - name: "â­ï¸ Deploy frontend to vercel"  
        uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORGANISATION_ID }}  #Required
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required 
          working-directory: ./client
