name: Frontend-Check

on:
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "âš¡ Checkout"
        uses: actions/checkout@v3
      
      - name: "ðŸ§ª Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: "ðŸ“¦ Install Dependencies"
        working-directory: ./client
        run: yarn install --frozen-lockfile

      - name: "ðŸŒ¹ Format Code"
        working-directory: ./client
        run: yarn format

      - name: "ðŸ§¶ Lint Code"
        working-directory: ./client
        run: yarn lint
        
      - name: "âœ… Run Unit Tests"
        working-directory: ./client
        run: yarn test

